"""empty message

Revision ID: 324c95a6cd75
Revises: 4ee3e59af136
Create Date: 2023-10-06 09:20:49.847977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324c95a6cd75'
down_revision = '4ee3e59af136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
